name: demo_utils_constants
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.7.0
  demo_analysis:
    path: ../demo_analysis
  dependency_validator: ^3.2.2
  very_good_analysis: ^4.0.0+1
dependencies:
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
