name: demo_utils_constants
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
    demo_analysis:
      path: ../demo_analysis
    dart_code_metrics: ^5.7.0
    dependency_validator: ^3.2.2
    very_good_analysis: ^4.0.0+1
