name: demo_analysis
publish_to: none
version: 0.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
  
dev_dependencies:
  dart_code_metrics: ^5.7.0
  dependency_validator: ^3.2.2
  very_good_analysis: ^4.0.0+1


