name: demo_http_api
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.18.0 <3.0.0"
  
dependencies:
  demo_data_models:
    path: ../demo_data_models
  demo_errors:
    path: ../demo_errors
  demo_utils_constants:
    path: ../demo_utils_constants
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  internet_connection_checker: ^1.0.0+1
  logging: ^1.1.1
  
dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.7.0
  demo_analysis:
    path: ../demo_analysis
  dependency_validator: ^3.2.2
  json_serializable: ^6.6.1
  test: ^1.24.1
  very_good_analysis: ^4.0.0+1
