name: demo_ui
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  demo_data_models:
    path: ../demo_data_models
  flutter:
    sdk: flutter

dev_dependencies:
  alchemist: ^0.6.0
  dart_code_metrics: ^5.7.0
  demo_analysis:
    path: ../demo_analysis
  demo_theme:
    path: ../demo_theme
  dependency_validator: ^3.2.2
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
